### ISSUE TITLE
xcvrd crash: Exception occured at CmisManagerTask thread due to TypeError

### ISSUE THREAD

**Issue by amnsinghal** [sonic-net/sonic-platform-common#379]
cmis.py:get_application() did not check 'NoneType' return from xcvr_eeprom.read().
```
Jun  1 23:32:49.924628 sonic ERR pmon#xcvrd[273]: Exception occured at CmisManagerTask thread due to TypeError("unsupported operand type(s) for >>: 'NoneType' and 'int'")
Jun  1 23:32:49.927284 sonic ERR pmon#xcvrd[273]: Traceback (most recent call last):
Jun  1 23:32:49.927284 sonic ERR pmon#xcvrd[273]:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 1666, in run
Jun  1 23:32:49.927301 sonic ERR pmon#xcvrd[273]:     self.task_worker()
Jun  1 23:32:49.927339 sonic ERR pmon#xcvrd[273]:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 1536, in task_worker
Jun  1 23:32:49.927375 sonic ERR pmon#xcvrd[273]:     need_update = self.is_cmis_application_update_required(api, appl, host_lanes_mask)
Jun  1 23:32:49.927394 sonic ERR pmon#xcvrd[273]:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 1162, in is_cmis_application_update_required
Jun  1 23:32:49.927413 sonic ERR pmon#xcvrd[273]:     elif app_old != api.get_application(lane):
Jun  1 23:32:49.927432 sonic ERR pmon#xcvrd[273]:   File "/usr/local/lib/python3.9/dist-packages/sonic_platform_base/sonic_xcvr/api/public/cmis.py", line 2000, in get_application
Jun  1 23:32:49.927447 sonic ERR pmon#xcvrd[273]:     appl = self.xcvr_eeprom.read(name) >> 4
Jun  1 23:32:49.927465 sonic ERR pmon#xcvrd[273]: TypeError: unsupported operand type(s) for >>: 'NoneType' and 'int'
Jun  1 23:32:49.927621 sonic ERR pmon#xcvrd[273]: Xcvrd: exception found at child thread CmisManagerTask due to TypeError("unsupported operand type(s) for >>: 'NoneType' and 'int'")
Jun  1 23:32:49.927621 sonic ERR pmon#xcvrd[273]: Exiting main loop as child thread raised exception!
Jun  1 23:32:49.944454 sonic INFO pmon#supervisord 2023-06-01 23:32:49,944 INFO exited: xcvrd (terminated by SIGKILL; not expected)
```

Similar issue fixed recently: https://github.com/sonic-net/sonic-platform-common/pull/371

**Comment by prgeor** [comment]
@jaganbal-a could you please take a look. Check with Anoop?

**Comment by jaganbal-a** [comment]
Issue is not reproducible in latest image.  
Please close the issue and reopen if the issue reproducible.
